file_type: csv
dataset_name: airlineDelayData
file_name: airline_2014
inbound_delimiter: ","
outbound_delimiter: "|"
outbound_file_type: "gzip"
output_file: "Datasets/airlineDelayData2014-2018.gz"
columns:
  - fl_date
  - op_carrier
  - op_carrier_fl_num
  - origin
  - dest
  - crs_dep_time
  - dep_time
  - dep_delay
  - taxi_out
  - wheels_off
  - wheels_on
  - taxi_in
  - crs_arr_time
  - arr_time
  - arr_delay
  - cancelled
  - cancellation_code
  - diverted
  - crs_elapsed_time
  - actual_elapsed_time
  - air_time
  - distance
  - carrier_delay
  - weather_delay
  - nas_delay
  - security_delay
  - late_aircraft_delay
